require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AudiosController do

  # This should return the minimal set of attributes required to create a valid
  # Audio. As you add validations to Audio, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "title" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AudiosController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all audios as @audios" do
      audio = Audio.create! valid_attributes
      get :index, {}, valid_session
      assigns(:audios).should eq([audio])
    end
  end

  describe "GET show" do
    it "assigns the requested audio as @audio" do
      audio = Audio.create! valid_attributes
      get :show, {:id => audio.to_param}, valid_session
      assigns(:audio).should eq(audio)
    end
  end

  describe "GET new" do
    it "assigns a new audio as @audio" do
      get :new, {}, valid_session
      assigns(:audio).should be_a_new(Audio)
    end
  end

  describe "GET edit" do
    it "assigns the requested audio as @audio" do
      audio = Audio.create! valid_attributes
      get :edit, {:id => audio.to_param}, valid_session
      assigns(:audio).should eq(audio)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Audio" do
        expect {
          post :create, {:audio => valid_attributes}, valid_session
        }.to change(Audio, :count).by(1)
      end

      it "assigns a newly created audio as @audio" do
        post :create, {:audio => valid_attributes}, valid_session
        assigns(:audio).should be_a(Audio)
        assigns(:audio).should be_persisted
      end

      it "redirects to the created audio" do
        post :create, {:audio => valid_attributes}, valid_session
        response.should redirect_to(Audio.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved audio as @audio" do
        # Trigger the behavior that occurs when invalid params are submitted
        Audio.any_instance.stub(:save).and_return(false)
        post :create, {:audio => { "title" => "invalid value" }}, valid_session
        assigns(:audio).should be_a_new(Audio)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Audio.any_instance.stub(:save).and_return(false)
        post :create, {:audio => { "title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested audio" do
        audio = Audio.create! valid_attributes
        # Assuming there are no other audios in the database, this
        # specifies that the Audio created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Audio.any_instance.should_receive(:update_attributes).with({ "title" => "MyString" })
        put :update, {:id => audio.to_param, :audio => { "title" => "MyString" }}, valid_session
      end

      it "assigns the requested audio as @audio" do
        audio = Audio.create! valid_attributes
        put :update, {:id => audio.to_param, :audio => valid_attributes}, valid_session
        assigns(:audio).should eq(audio)
      end

      it "redirects to the audio" do
        audio = Audio.create! valid_attributes
        put :update, {:id => audio.to_param, :audio => valid_attributes}, valid_session
        response.should redirect_to(audio)
      end
    end

    describe "with invalid params" do
      it "assigns the audio as @audio" do
        audio = Audio.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Audio.any_instance.stub(:save).and_return(false)
        put :update, {:id => audio.to_param, :audio => { "title" => "invalid value" }}, valid_session
        assigns(:audio).should eq(audio)
      end

      it "re-renders the 'edit' template" do
        audio = Audio.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Audio.any_instance.stub(:save).and_return(false)
        put :update, {:id => audio.to_param, :audio => { "title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested audio" do
      audio = Audio.create! valid_attributes
      expect {
        delete :destroy, {:id => audio.to_param}, valid_session
      }.to change(Audio, :count).by(-1)
    end

    it "redirects to the audios list" do
      audio = Audio.create! valid_attributes
      delete :destroy, {:id => audio.to_param}, valid_session
      response.should redirect_to(audios_url)
    end
  end

end
